apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: james-netshoot
  labels:
    k8s-app: james-netshoot
spec:
  selector:
    matchLabels:
      name: james-netshoot
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: james-netshoot
    spec:
      tolerations:
      - effect: NoExecute
        key: k3s-controlplane
        value: "true"

      containers:
      - name: james-netshoot
        image: jamesharr/ubuntu-netshoot:latest
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
